(function () {
  "use strict";

  window.__BRAND__ = {
    name: "Emojiland",
    tagline: "Copia y pega emojis gratis, sin registro",
    domain: "emojiland",

    categories: [
      {
        id: "smileys",
        label: "Caritas",
        icon: "\u{1F600}",
        items: [
          ["\u{1F600}", "cara sonriente"],
          ["\u{1F603}", "cara sonriente con ojos grandes"],
          ["\u{1F604}", "cara sonriente con ojos cerrados"],
          ["\u{1F601}", "cara sonriente con dientes"],
          ["\u{1F606}", "cara riendo con ojos cerrados"],
          ["\u{1F605}", "cara sonriente con sudor"],
          ["\u{1F923}", "muerto de risa"],
          ["\u{1F602}", "llorando de risa"],
          ["\u{1F642}", "cara ligeramente sonriente"],
          ["\u{1F643}", "cara al revés"],
          ["\u{1F609}", "cara guiñando un ojo"],
          ["\u{1F60A}", "cara sonriente con ojos entornados"],
          ["\u{1F607}", "cara sonriente con aureola"],
          ["\u{1F970}", "cara sonriente con corazones"],
          ["\u{1F60D}", "cara enamorada"],
          ["\u{1F929}", "cara con ojos de estrella"],
          ["\u{1F618}", "cara lanzando un beso"],
          ["\u{1F617}", "cara besando"],
          ["\u{1F61A}", "cara besando con ojos cerrados"],
          ["\u{1F619}", "cara besando sonriendo"],
          ["\u{1F972}", "cara sonriendo con lágrima"],
          ["\u{1F60B}", "cara saboreando comida"],
          ["\u{1F61B}", "cara sacando la lengua"],
          ["\u{1F61C}", "cara guiñando y sacando la lengua"],
          ["\u{1F92A}", "cara loca"],
          ["\u{1F61D}", "cara sacando la lengua con ojos cerrados"],
          ["\u{1F911}", "cara con dinero"],
          ["\u{1F917}", "cara abrazando"],
          ["\u{1F92D}", "cara con mano en la boca"],
          ["\u{1F92B}", "cara pidiendo silencio"],
          ["\u{1F914}", "cara pensativa"],
          ["\u{1F910}", "cara con cremallera"],
          ["\u{1F928}", "cara con ceja levantada"],
          ["\u{1F610}", "cara neutral"],
          ["\u{1F611}", "cara sin expresión"],
          ["\u{1F636}", "cara sin boca"],
          ["\u{1F60F}", "cara con sonrisa pícara"],
          ["\u{1F612}", "cara sin interés"],
          ["\u{1F644}", "cara con ojos en blanco"],
          ["\u{1F62C}", "cara haciendo mueca"],
          ["\u{1F925}", "cara mentirosa"],
          ["\u{1F60C}", "cara aliviada"],
          ["\u{1F614}", "cara pensativa triste"],
          ["\u{1F62A}", "cara con sueño"],
          ["\u{1F924}", "cara babeando"],
          ["\u{1F634}", "cara durmiendo"],
          ["\u{1F637}", "cara con mascarilla"],
          ["\u{1F912}", "cara con termómetro"],
          ["\u{1F915}", "cara con vendaje"],
          ["\u{1F922}", "cara con náuseas"],
          ["\u{1F92E}", "cara vomitando"],
          ["\u{1F975}", "cara acalorada"],
          ["\u{1F976}", "cara helada"],
          ["\u{1F635}", "cara mareada"],
          ["\u{1F92F}", "cabeza explotando"],
          ["\u{1F920}", "cara de vaquero"],
          ["\u{1F973}", "cara festejando"],
          ["\u{1F60E}", "cara con gafas de sol"],
          ["\u{1F913}", "cara empollona"],
          ["\u{1F9D0}", "cara con monóculo"],
          ["\u{1F615}", "cara confundida"],
          ["\u{1F61F}", "cara preocupada"],
          ["\u{1F641}", "cara ligeramente fruncida"],
          ["\u{1F62E}", "cara sorprendida"],
          ["\u{1F62F}", "cara asombrada"],
          ["\u{1F632}", "cara asombrada con boca abierta"],
          ["\u{1F633}", "cara sonrojada"],
          ["\u{1F97A}", "cara suplicante"],
          ["\u{1F626}", "cara con boca abierta"],
          ["\u{1F628}", "cara asustada"],
          ["\u{1F630}", "cara con ansiedad"],
          ["\u{1F625}", "cara triste aliviada"],
          ["\u{1F622}", "cara llorando"],
          ["\u{1F62D}", "cara llorando fuerte"],
          ["\u{1F631}", "cara gritando de miedo"],
          ["\u{1F616}", "cara confundida y molesta"],
          ["\u{1F623}", "cara perseverante"],
          ["\u{1F61E}", "cara decepcionada"],
          ["\u{1F613}", "cara con sudor frío"],
          ["\u{1F629}", "cara agotada"],
          ["\u{1F62B}", "cara agotada y cansada"],
          ["\u{1F971}", "cara bostezando"],
          ["\u{1F624}", "cara resoplando"],
          ["\u{1F621}", "cara furiosa"],
          ["\u{1F620}", "cara enfadada"],
          ["\u{1F92C}", "cara con lenguaje soez"],
          ["\u{1F608}", "cara sonriente traviesa"],
          ["\u{1F47F}", "cara enfadada traviesa"],
          ["\u{1F480}", "calavera"],
          ["☠️", "calavera y huesos cruzados"],
          ["\u{1F4A9}", "caca sonriente"],
          ["\u{1F921}", "cara de payaso"],
          ["\u{1F479}", "cara de ogro"],
          ["\u{1F47A}", "cara de duende"],
          ["\u{1F47B}", "fantasma"],
          ["\u{1F47D}", "alienígena"],
          ["\u{1F916}", "robot"],
          ["\u{1F63A}", "gato sonriente"],
          ["\u{1F638}", "gato sonriendo con ojos felices"],
          ["\u{1F639}", "gato llorando de risa"]
        ]
      },
      {
        id: "personas",
        label: "Personas",
        icon: "\u{1F44B}",
        items: [
          ["\u{1F44B}", "mano saludando"],
          ["\u{1F91A}", "mano levantada"],
          ["\u{1F590}️", "mano abierta"],
          ["✋", "mano en alto"],
          ["\u{1F44C}", "mano con dedos en ok"],
          ["\u{1F90C}", "dedos juntos"],
          ["\u{1F90F}", "pellizco"],
          ["✌️", "señal de victoria"],
          ["\u{1F91E}", "dedos cruzados"],
          ["\u{1FAF0}", "dedos en corazón"],
          ["\u{1F91F}", "te quiero en lenguaje de signos"],
          ["\u{1F918}", "cuernos con la mano"],
          ["\u{1F919}", "llamada con la mano"],
          ["\u{1F448}", "dedo señalando a la izquierda"],
          ["\u{1F449}", "dedo señalando a la derecha"],
          ["\u{1F446}", "dedo señalando hacia arriba"],
          ["\u{1F447}", "dedo señalando hacia abajo"],
          ["☝️", "dedo índice hacia arriba"],
          ["\u{1F44D}", "pulgar hacia arriba"],
          ["\u{1F44E}", "pulgar hacia abajo"],
          ["✊", "puño cerrado"],
          ["\u{1F44A}", "puño"],
          ["\u{1F91B}", "puño hacia la izquierda"],
          ["\u{1F91C}", "puño hacia la derecha"],
          ["\u{1F44F}", "aplausos"],
          ["\u{1F64C}", "manos celebrando"],
          ["\u{1F450}", "manos abiertas"],
          ["\u{1F932}", "manos juntas hacia arriba"],
          ["\u{1F91D}", "apretón de manos"],
          ["\u{1F64F}", "manos juntas orando"],
          ["✍️", "mano escribiendo"],
          ["\u{1F485}", "pintándose las uñas"],
          ["\u{1F933}", "selfie"],
          ["\u{1F4AA}", "bíceps flexionado"],
          ["\u{1F9B5}", "pierna"],
          ["\u{1F9B6}", "pie"],
          ["\u{1F442}", "oreja"],
          ["\u{1F443}", "nariz"],
          ["\u{1F9E0}", "cerebro"],
          ["\u{1F9B7}", "diente"],
          ["\u{1F440}", "ojos"],
          ["\u{1F441}️", "ojo"],
          ["\u{1F445}", "lengua"],
          ["\u{1F444}", "boca"],
          ["\u{1F476}", "bebé"],
          ["\u{1F9D2}", "niño o niña"],
          ["\u{1F466}", "niño"],
          ["\u{1F467}", "niña"],
          ["\u{1F9D1}", "persona adulta"],
          ["\u{1F468}", "hombre"],
          ["\u{1F469}", "mujer"],
          ["\u{1F9D3}", "persona mayor"],
          ["\u{1F474}", "anciano"],
          ["\u{1F475}", "anciana"],
          ["\u{1F930}", "mujer embarazada"],
          ["\u{1F47C}", "bebé ángel"],
          ["\u{1F385}", "papá noel"],
          ["\u{1F9B8}", "superhéroe"],
          ["\u{1F9D9}", "mago"],
          ["\u{1F9DB}", "vampiro"],
          ["\u{1F483}", "mujer bailando"],
          ["\u{1F57A}", "hombre bailando"]
        ]
      },
      {
        id: "animales",
        label: "Animales",
        icon: "\u{1F436}",
        items: [
          ["\u{1F436}", "perro"],
          ["\u{1F431}", "gato"],
          ["\u{1F42D}", "ratón"],
          ["\u{1F439}", "hámster"],
          ["\u{1F430}", "conejo"],
          ["\u{1F98A}", "zorro"],
          ["\u{1F43B}", "oso"],
          ["\u{1F43C}", "panda"],
          ["\u{1F428}", "koala"],
          ["\u{1F42F}", "tigre"],
          ["\u{1F981}", "león"],
          ["\u{1F42E}", "vaca"],
          ["\u{1F437}", "cerdo"],
          ["\u{1F438}", "rana"],
          ["\u{1F435}", "mono"],
          ["\u{1F648}", "mono tapándose los ojos"],
          ["\u{1F649}", "mono tapándose los oídos"],
          ["\u{1F64A}", "mono tapándose la boca"],
          ["\u{1F414}", "gallina"],
          ["\u{1F427}", "pingüino"],
          ["\u{1F426}", "pájaro"],
          ["\u{1F424}", "pollito"],
          ["\u{1F986}", "pato"],
          ["\u{1F985}", "águila"],
          ["\u{1F989}", "búho"],
          ["\u{1F987}", "murciélago"],
          ["\u{1F43A}", "lobo"],
          ["\u{1F417}", "jabalí"],
          ["\u{1F434}", "caballo"],
          ["\u{1F984}", "unicornio"],
          ["\u{1F41D}", "abeja"],
          ["\u{1F41B}", "oruga"],
          ["\u{1F98B}", "mariposa"],
          ["\u{1F40C}", "caracol"],
          ["\u{1F41E}", "mariquita"],
          ["\u{1F41C}", "hormiga"],
          ["\u{1F982}", "escorpión"],
          ["\u{1F422}", "tortuga"],
          ["\u{1F40D}", "serpiente"],
          ["\u{1F98E}", "lagarto"],
          ["\u{1F419}", "pulpo"],
          ["\u{1F991}", "calamar"],
          ["\u{1F990}", "gamba"],
          ["\u{1F980}", "cangrejo"],
          ["\u{1F421}", "pez globo"],
          ["\u{1F420}", "pez tropical"],
          ["\u{1F41F}", "pez"],
          ["\u{1F42C}", "delfín"],
          ["\u{1F433}", "ballena"],
          ["\u{1F40B}", "ballena jorobada"],
          ["\u{1F988}", "tiburón"],
          ["\u{1F40A}", "cocodrilo"],
          ["\u{1F406}", "leopardo"],
          ["\u{1F993}", "cebra"],
          ["\u{1F98D}", "gorila"],
          ["\u{1F9A7}", "orangután"],
          ["\u{1F418}", "elefante"],
          ["\u{1F99B}", "hipopótamo"],
          ["\u{1F98F}", "rinoceronte"],
          ["\u{1F42B}", "camello"],
          ["\u{1F992}", "jirafa"],
          ["\u{1F998}", "canguro"],
          ["\u{1F404}", "vaca de granja"],
          ["\u{1F416}", "cerdo de granja"],
          ["\u{1F411}", "oveja"],
          ["\u{1F410}", "cabra"],
          ["\u{1F413}", "gallo"],
          ["\u{1F983}", "pavo"],
          ["\u{1F415}", "perro de raza"],
          ["\u{1F429}", "caniche"],
          ["\u{1F408}", "gato de raza"],
          ["\u{1F407}", "conejo pequeño"],
          ["\u{1F43F}️", "ardilla"],
          ["\u{1F994}", "erizo"]
        ]
      },
      {
        id: "comida",
        label: "Comida",
        icon: "\u{1F354}",
        items: [
          ["\u{1F34F}", "manzana verde"],
          ["\u{1F34E}", "manzana roja"],
          ["\u{1F350}", "pera"],
          ["\u{1F34A}", "naranja"],
          ["\u{1F34B}", "limón"],
          ["\u{1F34C}", "plátano"],
          ["\u{1F349}", "sandía"],
          ["\u{1F347}", "uvas"],
          ["\u{1F353}", "fresa"],
          ["\u{1FAD0}", "arándanos"],
          ["\u{1F348}", "melón"],
          ["\u{1F352}", "cerezas"],
          ["\u{1F351}", "melocotón"],
          ["\u{1F96D}", "mango"],
          ["\u{1F34D}", "piña"],
          ["\u{1F965}", "coco"],
          ["\u{1F95D}", "kiwi"],
          ["\u{1F345}", "tomate"],
          ["\u{1F346}", "berenjena"],
          ["\u{1F951}", "aguacate"],
          ["\u{1F966}", "brócoli"],
          ["\u{1F96C}", "lechuga"],
          ["\u{1F952}", "pepino"],
          ["\u{1F336}️", "chile picante"],
          ["\u{1FAD1}", "pimiento"],
          ["\u{1F33D}", "maíz"],
          ["\u{1F955}", "zanahoria"],
          ["\u{1F9C4}", "ajo"],
          ["\u{1F9C5}", "cebolla"],
          ["\u{1F954}", "patata"],
          ["\u{1F360}", "boniato"],
          ["\u{1F950}", "croissant"],
          ["\u{1F956}", "baguette"],
          ["\u{1F35E}", "pan"],
          ["\u{1F968}", "pretzel"],
          ["\u{1F96F}", "bagel"],
          ["\u{1F9C0}", "queso"],
          ["\u{1F95A}", "huevo"],
          ["\u{1F373}", "huevo frito"],
          ["\u{1F9C8}", "mantequilla"],
          ["\u{1F95E}", "tortitas"],
          ["\u{1F9C7}", "gofre"],
          ["\u{1F953}", "beicon"],
          ["\u{1F969}", "filete de carne"],
          ["\u{1F357}", "muslo de pollo"],
          ["\u{1F356}", "hueso con carne"],
          ["\u{1F32D}", "perrito caliente"],
          ["\u{1F354}", "hamburguesa"],
          ["\u{1F35F}", "patatas fritas"],
          ["\u{1F355}", "pizza"],
          ["\u{1F96A}", "sándwich"],
          ["\u{1F32E}", "taco"],
          ["\u{1F32F}", "burrito"],
          ["\u{1FAD4}", "tamal"],
          ["\u{1F959}", "pan de pita relleno"],
          ["\u{1F9C6}", "falafel"],
          ["\u{1F957}", "ensalada"],
          ["\u{1F37F}", "palomitas"],
          ["\u{1F9C2}", "sal"],
          ["\u{1F96B}", "lata de conserva"],
          ["\u{1F371}", "bento"],
          ["\u{1F363}", "sushi"],
          ["\u{1F364}", "gamba tempura"],
          ["\u{1F359}", "bola de arroz"],
          ["\u{1F35A}", "arroz"],
          ["\u{1F35C}", "fideos en caldo"],
          ["\u{1F35D}", "espaguetis"],
          ["\u{1F372}", "estofado"],
          ["\u{1F35B}", "curry con arroz"],
          ["\u{1F370}", "porción de pastel"],
          ["\u{1F382}", "tarta de cumpleaños"],
          ["\u{1F36E}", "flan"],
          ["\u{1F36D}", "piruleta"],
          ["\u{1F36C}", "caramelo"],
          ["\u{1F36B}", "chocolate"],
          ["\u{1F369}", "dónut"],
          ["\u{1F36A}", "galleta"],
          ["\u{1F366}", "helado suave"],
          ["\u{1F368}", "helado"],
          ["\u{1F367}", "granizado"],
          ["☕", "café"],
          ["\u{1F375}", "té"],
          ["\u{1F9CB}", "té con burbujas"],
          ["\u{1F964}", "refresco"],
          ["\u{1F9C3}", "zumo en brik"],
          ["\u{1F37A}", "cerveza"],
          ["\u{1F377}", "copa de vino"],
          ["\u{1F942}", "brindis"],
          ["\u{1F37E}", "champán"]
        ]
      },
      {
        id: "actividades",
        label: "Actividades",
        icon: "⚽",
        items: [
          ["⚽", "balón de fútbol"],
          ["\u{1F3C0}", "balón de baloncesto"],
          ["\u{1F3C8}", "balón de fútbol americano"],
          ["⚾", "pelota de béisbol"],
          ["\u{1F3BE}", "pelota de tenis"],
          ["\u{1F3D0}", "balón de voleibol"],
          ["\u{1F3C9}", "balón de rugby"],
          ["\u{1F3B1}", "bola de billar"],
          ["\u{1F3D3}", "ping pong"],
          ["\u{1F3F8}", "bádminton"],
          ["\u{1F94A}", "boxeo"],
          ["\u{1F94B}", "artes marciales"],
          ["⛳", "golf"],
          ["\u{1F3F9}", "arco y flecha"],
          ["\u{1F3A3}", "pesca"],
          ["\u{1F94C}", "curling"],
          ["⛷️", "esquí"],
          ["\u{1F3C2}", "snowboard"],
          ["\u{1F3C4}", "surf"],
          ["\u{1F6B4}", "ciclismo"],
          ["\u{1F3CA}", "natación"],
          ["\u{1F938}", "gimnasia"],
          ["\u{1F3AF}", "diana"],
          ["\u{1F3AE}", "videojuegos"],
          ["\u{1F3B2}", "dado"],
          ["\u{1F9E9}", "puzle"],
          ["\u{1F3B3}", "bolos"],
          ["\u{1F3A8}", "paleta de pintor"],
          ["\u{1F3AD}", "máscaras de teatro"],
          ["\u{1F3A4}", "micrófono"],
          ["\u{1F3A7}", "auriculares"],
          ["\u{1F3BC}", "partitura"],
          ["\u{1F3B9}", "piano"],
          ["\u{1F941}", "tambor"],
          ["\u{1F3B8}", "guitarra"],
          ["\u{1F3BA}", "trompeta"],
          ["\u{1F3C6}", "trofeo"],
          ["\u{1F947}", "medalla de oro"],
          ["\u{1F397}️", "lazo conmemorativo"],
          ["\u{1F39F}️", "entrada"]
        ]
      },
      {
        id: "viajes",
        label: "Viajes",
        icon: "✈️",
        items: [
          ["\u{1F697}", "coche"],
          ["\u{1F695}", "taxi"],
          ["\u{1F699}", "todoterreno"],
          ["\u{1F68C}", "autobús"],
          ["\u{1F68E}", "trolebús"],
          ["\u{1F3CE}️", "coche de carreras"],
          ["\u{1F693}", "coche de policía"],
          ["\u{1F691}", "ambulancia"],
          ["\u{1F692}", "camión de bomberos"],
          ["\u{1F690}", "furgoneta"],
          ["\u{1F69A}", "camión"],
          ["\u{1F69B}", "camión articulado"],
          ["\u{1F69C}", "tractor"],
          ["\u{1F6F5}", "escúter"],
          ["\u{1F3CD}️", "motocicleta"],
          ["\u{1F6B2}", "bicicleta"],
          ["\u{1F6F4}", "patinete"],
          ["✈️", "avión"],
          ["\u{1F6EB}", "avión despegando"],
          ["\u{1F6EC}", "avión aterrizando"],
          ["\u{1F680}", "cohete"],
          ["\u{1F6F8}", "ovni"],
          ["\u{1F681}", "helicóptero"],
          ["⛵", "velero"],
          ["\u{1F6A4}", "lancha"],
          ["\u{1F6F3}️", "crucero"],
          ["⚓", "ancla"],
          ["\u{1F6A2}", "barco"],
          ["\u{1F682}", "locomotora"],
          ["\u{1F686}", "tren"],
          ["\u{1F687}", "metro"],
          ["\u{1F689}", "estación de tren"],
          ["\u{1F5FD}", "estatua de la libertad"],
          ["\u{1F5FC}", "torre"],
          ["\u{1F3F0}", "castillo"],
          ["\u{1F3EF}", "castillo japonés"],
          ["\u{1F3A1}", "noria"],
          ["\u{1F3A2}", "montaña rusa"],
          ["\u{1F3D6}️", "playa"],
          ["\u{1F3DD}️", "isla desierta"],
          ["\u{1F3D4}️", "montaña nevada"],
          ["\u{1F30B}", "volcán"],
          ["\u{1F5FB}", "monte Fuji"],
          ["\u{1F3D5}️", "camping"],
          ["⛺", "tienda de campaña"],
          ["\u{1F305}", "amanecer"],
          ["\u{1F307}", "atardecer en la ciudad"],
          ["\u{1F303}", "noche estrellada"],
          ["\u{1F306}", "anochecer"],
          ["\u{1F309}", "puente de noche"],
          ["\u{1F3D9}️", "paisaje urbano"]
        ]
      },
      {
        id: "objetos",
        label: "Objetos",
        icon: "\u{1F4A1}",
        items: [
          ["⌚", "reloj de pulsera"],
          ["\u{1F4F1}", "móvil"],
          ["\u{1F4BB}", "portátil"],
          ["⌨️", "teclado"],
          ["\u{1F5A5}️", "ordenador de sobremesa"],
          ["\u{1F5A8}️", "impresora"],
          ["\u{1F5B1}️", "ratón de ordenador"],
          ["\u{1F4BD}", "disco"],
          ["\u{1F4BE}", "disquete"],
          ["\u{1F4BF}", "cd"],
          ["\u{1F4C0}", "dvd"],
          ["\u{1F4F7}", "cámara de fotos"],
          ["\u{1F4F8}", "cámara con flash"],
          ["\u{1F3A5}", "cámara de vídeo"],
          ["\u{1F4F9}", "videocámara"],
          ["\u{1F4FA}", "televisión"],
          ["\u{1F4FB}", "radio"],
          ["\u{1F399}️", "micrófono de estudio"],
          ["⏱️", "cronómetro"],
          ["⏰", "despertador"],
          ["⌛", "reloj de arena"],
          ["\u{1F50B}", "batería"],
          ["\u{1F50C}", "enchufe"],
          ["\u{1F4A1}", "bombilla"],
          ["\u{1F526}", "linterna"],
          ["\u{1F56F}️", "vela"],
          ["\u{1F9EF}", "extintor"],
          ["\u{1F6E2}️", "barril"],
          ["\u{1F4B5}", "billete de dólar"],
          ["\u{1F4B0}", "saco de dinero"],
          ["\u{1F4B3}", "tarjeta de crédito"],
          ["\u{1F9FE}", "recibo"],
          ["✉️", "sobre"],
          ["\u{1F4E9}", "sobre con flecha"],
          ["\u{1F4E6}", "paquete"],
          ["\u{1F4EB}", "buzón"],
          ["\u{1F4D6}", "libro abierto"],
          ["\u{1F4DA}", "pila de libros"],
          ["\u{1F4DD}", "memo"],
          ["✏️", "lápiz"],
          ["\u{1F58A}️", "bolígrafo"],
          ["\u{1F58C}️", "pincel"],
          ["\u{1F4CC}", "chincheta"],
          ["\u{1F4CE}", "clip"],
          ["✂️", "tijeras"],
          ["\u{1F512}", "candado cerrado"],
          ["\u{1F511}", "llave"],
          ["\u{1F528}", "martillo"],
          ["\u{1FA93}", "hacha"],
          ["\u{1F527}", "llave inglesa"],
          ["⚙️", "engranaje"],
          ["\u{1F9F2}", "imán"],
          ["\u{1F52C}", "microscopio"],
          ["\u{1F52D}", "telescopio"],
          ["\u{1F48A}", "pastilla"],
          ["\u{1F489}", "jeringuilla"],
          ["\u{1FA79}", "tirita"],
          ["\u{1F9EC}", "adn"],
          ["\u{1F52E}", "bola de cristal"],
          ["\u{1F381}", "regalo"]
        ]
      },
      {
        id: "simbolos",
        label: "Símbolos",
        icon: "❤️",
        items: [
          ["❤️", "corazón rojo"],
          ["\u{1F9E1}", "corazón naranja"],
          ["\u{1F49B}", "corazón amarillo"],
          ["\u{1F49A}", "corazón verde"],
          ["\u{1F499}", "corazón azul"],
          ["\u{1F49C}", "corazón morado"],
          ["\u{1F5A4}", "corazón negro"],
          ["\u{1F90D}", "corazón blanco"],
          ["\u{1F90E}", "corazón marrón"],
          ["\u{1F494}", "corazón roto"],
          ["❣️", "signo de exclamación de corazón"],
          ["\u{1F495}", "dos corazones"],
          ["\u{1F49E}", "corazones girando"],
          ["\u{1F493}", "corazón latiendo"],
          ["\u{1F497}", "corazón creciendo"],
          ["\u{1F496}", "corazón brillante"],
          ["\u{1F498}", "corazón con flecha"],
          ["\u{1F49D}", "corazón con lazo"],
          ["✅", "marca de verificación"],
          ["❌", "marca de cruz"],
          ["❓", "signo de interrogación"],
          ["❗", "signo de exclamación"],
          ["⚠️", "advertencia"],
          ["\u{1F51E}", "mayores de 18"],
          ["♻️", "reciclaje"],
          ["✨", "destellos"],
          ["⭐", "estrella"],
          ["\u{1F31F}", "estrella brillante"],
          ["\u{1F4AB}", "estrella fugaz"],
          ["\u{1F4A5}", "explosión"],
          ["\u{1F4A2}", "símbolo de enfado"],
          ["\u{1F4A6}", "gotas de sudor"],
          ["\u{1F4A8}", "nube de velocidad"],
          ["\u{1F573}️", "agujero"],
          ["\u{1F4AC}", "bocadillo de diálogo"],
          ["\u{1F4AD}", "bocadillo de pensamiento"],
          ["\u{1F525}", "fuego"],
          ["♥️", "palo de corazones"],
          ["♦️", "palo de diamantes"],
          ["♣️", "palo de tréboles"],
          ["♠️", "palo de picas"],
          ["\u{1F197}", "botón ok"],
          ["\u{1F195}", "botón nuevo"],
          ["\u{1F51D}", "botón top"],
          ["\u{1F51C}", "botón próximamente"],
          ["\u{1F519}", "botón atrás"],
          ["Ⓜ️", "letra m en círculo"],
          ["\u{1F522}", "números"],
          ["\u{1F524}", "letras"],
          ["➕", "signo más"],
          ["➖", "signo menos"],
          ["✖️", "signo multiplicar"],
          ["➗", "signo dividir"],
          ["♾️", "infinito"],
          ["\u{1F4AF}", "cien puntos"]
        ]
      },
      {
        id: "banderas",
        label: "Banderas",
        icon: "\u{1F3F3}️",
        items: [
          ["\u{1F3F3}️", "bandera blanca"],
          ["\u{1F3F4}", "bandera negra"],
          ["\u{1F3C1}", "bandera de cuadros"],
          ["\u{1F6A9}", "banderín rojo"],
          ["\u{1F3F3}️‍\u{1F308}", "bandera arcoíris"],
          ["\u{1F1EA}\u{1F1F8}", "España"],
          ["\u{1F1F2}\u{1F1FD}", "México"],
          ["\u{1F1E6}\u{1F1F7}", "Argentina"],
          ["\u{1F1E8}\u{1F1F4}", "Colombia"],
          ["\u{1F1E8}\u{1F1F1}", "Chile"],
          ["\u{1F1F5}\u{1F1EA}", "Perú"],
          ["\u{1F1FB}\u{1F1EA}", "Venezuela"],
          ["\u{1F1EA}\u{1F1E8}", "Ecuador"],
          ["\u{1F1EC}\u{1F1F9}", "Guatemala"],
          ["\u{1F1E8}\u{1F1FA}", "Cuba"],
          ["\u{1F1E7}\u{1F1F4}", "Bolivia"],
          ["\u{1F1E9}\u{1F1F4}", "República Dominicana"],
          ["\u{1F1ED}\u{1F1F3}", "Honduras"],
          ["\u{1F1F5}\u{1F1FE}", "Paraguay"],
          ["\u{1F1F8}\u{1F1FB}", "El Salvador"],
          ["\u{1F1F3}\u{1F1EE}", "Nicaragua"],
          ["\u{1F1E8}\u{1F1F7}", "Costa Rica"],
          ["\u{1F1F5}\u{1F1E6}", "Panamá"],
          ["\u{1F1FA}\u{1F1FE}", "Uruguay"],
          ["\u{1F1FA}\u{1F1F8}", "Estados Unidos"],
          ["\u{1F1EC}\u{1F1E7}", "Reino Unido"],
          ["\u{1F1EB}\u{1F1F7}", "Francia"],
          ["\u{1F1E9}\u{1F1EA}", "Alemania"],
          ["\u{1F1EE}\u{1F1F9}", "Italia"],
          ["\u{1F1F5}\u{1F1F9}", "Portugal"],
          ["\u{1F1E7}\u{1F1F7}", "Brasil"],
          ["\u{1F1EF}\u{1F1F5}", "Japón"],
          ["\u{1F1E8}\u{1F1F3}", "China"],
          ["\u{1F1F0}\u{1F1F7}", "Corea del Sur"],
          ["\u{1F1E8}\u{1F1E6}", "Canadá"],
          ["\u{1F1E6}\u{1F1FA}", "Australia"],
          ["\u{1F1EE}\u{1F1F3}", "India"],
          ["\u{1F1F7}\u{1F1FA}", "Rusia"],
          ["\u{1F1F3}\u{1F1F1}", "Países Bajos"],
          ["\u{1F1E7}\u{1F1EA}", "Bélgica"],
          ["\u{1F1E8}\u{1F1ED}", "Suiza"],
          ["\u{1F1F8}\u{1F1EA}", "Suecia"],
          ["\u{1F1F3}\u{1F1F4}", "Noruega"],
          ["\u{1F1E9}\u{1F1F0}", "Dinamarca"],
          ["\u{1F1F5}\u{1F1F1}", "Polonia"],
          ["\u{1F1EC}\u{1F1F7}", "Grecia"],
          ["\u{1F1F9}\u{1F1F7}", "Turquía"],
          ["\u{1F1F2}\u{1F1E6}", "Marruecos"],
          ["\u{1F1EA}\u{1F1EC}", "Egipto"],
          ["\u{1F1FF}\u{1F1E6}", "Sudáfrica"]
        ]
      }
    ],

    usos: [
      { icon: "\u{1F37D}️", title: "Cartas de restaurantes", text: "Añade emojis junto a cada plato (\u{1F335} vegano, \u{1F336}️ picante, ⭐ recomendado) para que la carta se lea de un vistazo, en papel o en la carta digital con QR." },
      { icon: "⭐", title: "Reseñas y testimonios", text: "Ilustra valoraciones de clientes con caritas y estrellas que refuercen el mensaje sin ocupar espacio extra en redes sociales o en tu web." },
      { icon: "\u{1F511}", title: "Llaveros para eventos", text: "Genera combinaciones de emojis únicas para identificar mesas, entradas o grupos en bodas, congresos y fiestas — fáciles de imprimir en llaveros o tarjetas." },
      { icon: "\u{1F4F6}", title: "Carteles de wifi para alojamientos", text: "Copia el emoji de wifi \u{1F4F6} y combínalo con la contraseña en el cartel de tu hotel, apartamento turístico o cafetería." },
      { icon: "\u{1F4AC}", title: "Redes sociales y chats", text: "Copia y pega emojis directamente en Instagram, WhatsApp, TikTok o Twitter/X sin depender del teclado limitado de tu móvil o del selector de tu ordenador." },
      { icon: "\u{1F4CA}", title: "Presentaciones y documentos", text: "Añade emojis a diapositivas, informes o documentos de trabajo para destacar ideas clave sin insertar imágenes ni iconos externos." },
      { icon: "\u{1F3AB}", title: "Invitaciones y tarjetas", text: "Diseña invitaciones de cumpleaños, bodas o eventos con emojis temáticos que le dan un toque personal sin necesidad de diseño gráfico." },
      { icon: "\u{1F4E7}", title: "Email marketing", text: "Los emojis en el asunto del correo aumentan la tasa de apertura; cópialos aquí y pégalos directamente en tu plataforma de email." }
    ],

    faqs: [
      { q: "¿Es gratis copiar emojis en esta web?", a: "Sí, completamente gratis y sin límite de uso. No hace falta crear una cuenta ni instalar ninguna aplicación: entras, buscas el emoji que necesitas y lo copias." },
      { q: "¿Cómo copio un emoji para pegarlo después?", a: "Haz clic o toca el emoji que quieras. Se copia automáticamente a tu portapapeles y verás un aviso de confirmación. Después solo tienes que pegarlo (Ctrl+V o mantener pulsado y elegir «Pegar») donde quieras usarlo." },
      { q: "¿Los emojis se ven igual en todos los dispositivos?", a: "El diseño del emoji (colores y forma exactos) depende del sistema operativo o la app donde lo pegues — iOS, Android, WhatsApp o Windows pueden mostrar una versión ligeramente distinta del mismo emoji, pero el significado y el código son siempre los mismos." },
      { q: "¿Puedo usar los emojis en mi negocio o proyecto comercial?", a: "Sí. Los emojis son caracteres Unicode estándar, de uso libre en cualquier contexto personal o comercial: cartas de restaurantes, redes sociales, marketing, papelería, etc." },
      { q: "¿Por qué no se copia el emoji al hacer clic?", a: "Algunos navegadores antiguos o configuraciones de privacidad muy estrictas bloquean el acceso automático al portapapeles. Si ves que no se copia, prueba a recargar la página o a mantener pulsado el emoji durante un instante." },
      { q: "¿Necesito instalar un teclado de emojis?", a: "No. Esta web funciona como un selector de emojis online que sustituye al teclado de emojis del móvil u ordenador — útil sobre todo en ordenadores de escritorio, donde buscar un emoji concreto suele ser incómodo." },
      { q: "¿Puedo buscar un emoji por su nombre?", a: "Sí, usa el buscador de la parte superior de la herramienta y escribe una palabra clave (por ejemplo «corazón» o «pizza») para filtrar al instante entre todas las categorías." },
      { q: "¿Qué es la lista de favoritos y para qué sirve?", a: "Al pulsar la estrella de un emoji lo guardas en tus favoritos (solo en tu navegador). Desde ahí puedes descargar tu selección como archivo de texto para guardarla o compartirla." }
    ],

    steps: [
      { icon: "\u{1F50D}", title: "Busca o navega", text: "Escribe una palabra clave en el buscador o navega por las categorías con las pestañas, igual que en el selector de emojis de tu móvil." },
      { icon: "\u{1F446}", title: "Toca el emoji", text: "Haz clic o toca el emoji que quieras usar. Se copia al instante a tu portapapeles — verás una confirmación en pantalla." },
      { icon: "\u{1F4CB}", title: "Pégalo donde quieras", text: "Ve a tu chat, documento, red social o carta digital y pega el emoji con Ctrl+V (o mantén pulsado y elige «Pegar» en el móvil)." }
    ]
  };
})();
